name: Build, Test and Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

jobs:
  build_test_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test:ci
